site_name: FlowSieve
site_url: https://bastorer.github.io/documentation_development/
repo_url: https://github.com/bastorer/documentation_development
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Theory:
      - Helmholtz Decomposition: theory/helmholtz-decomposition.md
      - Mimetic Operators: theory/mimetic-operators.md
  - Examples: examples/index.md
#  - API Reference: api/index.html

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
